apiVersion: apps/v1
kind: Deployment
metadata:
        name : hello-world
spec: 
        selector:
                matchLabels:
                        run: lb-example
        replicas: 2
        template:
                metadata:
                        labels:
                                run: lb-example
                spec:
                        containers:
                                - name: hello-world
                                  image: gcr.io/google-samples/node-hello:1.0
                                  ports:
                                        - containerPort: 8080
                                          protocol: TCP
